# Site settings
title: Georgios Lampropoulos
email: g.lampropoulos1987@gmail.com
url: https://github.com/krampadance
description: "Personal website of Georgios Lampropoulos, a Software Engineer familiar with Data and AI."
keywords: "Georgios Lampropoulos, Software Engineer, Data, AI"
skills: "Software Engineer - LLM - RAG - API Development"
meta_author: Georgios Lampropoulos

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 3f6c7a
  primary-rgb: "63,108,122"
  secondary: 1f2937
  secondary-dark: 111827

# Footer settings
footer:
  copyright: Georgios Lampropoulos
  location: Athens, GR
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/krampadance

# Postal address (add as many lines as necessary)
address:
  - line: Georgios Lampropoulos
  - line: Laertou 47
  - line: Athens
  - line: 16121
  - line: Greece

# Credits content
credits: 'Created using <a href="https://github.com/jeromelachaud/freelancer-theme">Freelancer theme</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
